### ISSUE TITLE
add LICENSE.md

### ISSUE THREAD

**Issue by shanejonas** [zmitton/eth-proof#11]
I see in your `package.json` has `ISC`. Could you add a `LICENSE.md` to the repo to make it more clear on github what the license is?

**Comment by zmitton** [comment]
I don't really know much about these. Pristine seems to use apache, but I thought MIT was more permissive. Any thoughts? I prefer the most permissive possible

**Comment by shanejonas** [comment]
Apache 2.0, MIT, and ISC are all permissive licenses.

I prefer Apache 2.0, it has more legalese in it, which is a turn off for some people, but better for commercial adoption (just IMO, I'm not a lawyer 😂 ).

**Comment by shanejonas** [comment]
just not GPL lol

**Comment by shanejonas** [comment]
here is a great resource from github itself on the subject:

[choosealicense.com](http://choosealicense.com)
> A site to provide non-judgmental guidance on choosing a license for your open source project

**Comment by zmitton** [comment]
Ok thanks. I merged in pristine but went with the MIT license. The resource said thats what most NPM packages use
