### ISSUE TITLE
Resource temporarily unavailable Issue

### ISSUE THREAD

**Issue by abhayks1** [zmitton/eth-proof#3]
Hi,

I was testing eth proof library to getAccountProof with a local chain setup.

Below is my code:
epObjectWithChainData = new EP(new Web3.providers.HttpProvider("http://127.0.0.1:9546"), blockHash, chainDataPath)

chainDataPath is local running geth geth/chaindata path.
epObjectWithChainData.getAccountProof(accountAddress).then(function(proof){
      console.log("\n===========accountProofWithChainData===========\n", proof);
    }) 

While running the code, it gives below error:
"OpenError: IO error: lock geth/chaindata/LOCK: Resource temporarily unavailable"

Any suggestion how to fix it?

Thank You
Abhay

**Comment by zmitton** [comment]
This error is because you are running your Ethereum client at the same time. unfortunately you have to turn it off in order to allow another process to view the chaindata

**Comment by abhayks1** [comment]
@zmitton Thank you for the reply. Yes tested locally and running multiple process caused this error.
Only a single process can access chaindata at a time.

**Comment by zmitton** [comment]
ok, I'm closing the issue because this is mentioned in the README
