### ISSUE TITLE
Error: the string "transaction not found" was thrown, throw an Error :)

### ISSUE THREAD

**Issue by noot** [zmitton/eth-proof#4]
trying to write some tests for a contact and getting this error at this line:

`let proof = await eP.getTransactionProof(txHash);
`
```
 Error: the string "transaction not found" was thrown, throw an Error :)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

```
txHash is the hash of a previous transaction. the error seems like txHash isn't valid, but it should be.

here's where I'm generating the txHash:

```
    	let holdBalanceHash = await contract.holdSafeBalanceForType(10, 1, 100, {from: addressA});
        txHash = holdBalanceHash.tx;
```

txHash seems to be ok, so I'm not sure where this is going wrong.
any help is much appreciated!

**Comment by zmitton** [comment]
whats failing is probably his function: `web3.eth.getTransaction(txHash)`, so the transaction is not mined or included in the blockchain at time of request. I'd make sure everything is happening in the right order and that you have initiallized both `eP` and your `contract` with the same `provider`.

let me know if that helps
